/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.vue'],
  theme: {
    fontFamily: {
      pretendard: ['Pretendard'],
    },
    extend: {
      colors: {
        background: {
          80: 'rgba(255, 255, 255, 0.8)',
          90: 'rgba(255, 255, 255, 0.9)',
          100: '#FFF',
        },
        foreground: {
          10: 'rgba(2, 8, 23, 0.1)',
          50: 'rgba(2, 8, 23, 0.5)',
          80: 'rgba(2, 8, 23, 0.8)',
          90: 'rgba(2, 8, 23, 0.9)',
          100: '#020817',
        },
        dark: {
          50: 'rgba(226, 232, 240, 0.5)',
          80: 'rgba(226, 232, 240, 0.8)',
          90: 'rgba(226, 232, 240, 0.9)',
          100: '#E2E8F0',
          200: '#CBD5E1',
        },
        ring: {
          80: 'rgba(37, 99, 235, 0.8)',
          90: 'rgba(37, 99, 235, 0.9)',
          100: '#2563EB',
        },
        primary: {
          10: 'rgba(37, 99, 235, 0.1)',
          20: 'rgba(37, 99, 235, 0.2)',
          50: 'rgba(37, 99, 235, 0.5)',
          80: 'rgba(37, 99, 235, 0.8)',
          90: 'rgba(37, 99, 235, 0.9)',
          100: '#2563EB',
          200: '#1D5BD8',
        },
        'primary-foreground': {
          80: 'rgba(248, 250, 252, 0.8)',
          90: 'rgba(248, 250, 252, 0.9)',
          100: '#F8FAFC',
        },
        secondary: {
          80: 'rgba(241, 245, 249, 0.8)',
          90: 'rgba(241, 245, 249, 0.9)',
          100: '#F1F5F9',
        },
        'secondary-solid': {
          80: '#F1F5F9',
          90: '#F1F5F9',
          100: '#F1F5F9',
        },
        'secondary-foreground': {
          80: 'rgba(15, 23, 42, 0.8)',
          90: 'rgba(15, 23, 42, 0.9)',
          100: '#0F172A',
        },
        destructive: {
          10: 'rgba(239, 68, 68, 0.1)',
          50: 'rgba(239, 68, 68, 0.5)',
          80: 'rgba(239, 68, 68, 0.8)',
          90: 'rgba(239, 68, 68, 0.9)',
          100: '#EF4444',
        },
        'destructive-foreground': {
          80: 'rgba(248, 250, 252, 0.8)',
          90: 'rgba(248, 250, 252, 0.9)',
          100: '#F8FAFC',
        },
        muted: {
          40: 'rgba(241, 245, 249, 0.4)',
          50: 'rgba(241, 245, 249, 0.5)',
          80: 'rgba(241, 245, 249, 0.8)',
          90: 'rgba(241, 245, 249, 0.9)',
          100: '#F1F5F9',
        },
        'muted-foreground': {
          50: 'rgba(100, 116, 139, 0.5)',
          60: 'rgba(100, 116, 139, 0.6)',
          70: 'rgba(100, 116, 139, 0.7)',
          80: 'rgba(100, 116, 139, 0.8)',
          90: 'rgba(100, 116, 139, 0.9)',
          100: '#64748B',
        },
        accent: {
          50: 'rgba(241, 245, 249, 0.5)',
          80: 'rgba(241, 245, 249, 0.8)',
          90: 'rgba(241, 245, 249, 0.9)',
          100: '#F1F5F9',
        },
        'accent-foreground': {
          80: 'rgba(15, 23, 42, 0.8)',
          90: 'rgba(15, 23, 42, 0.9)',
          100: '#0F172A',
        },
        'deep-orange': {
          10: '#FFF0E6',
          100: '#E66000',
        },
        // 디자인 시스템 2차
        // Primitives Variables
        base: {
          b: {
            white: '#FFFFFF',
            black: '#0A0E15',
          },
        },
        neutral: {
          b: {
            gray: {
              25: '#FCFCFD',
              50: '#F9FAFB',
              100: '#F3F4F6',
              200: '#E5E7EB',
              300: '#D2D6DB',
              400: '#9DA4AE',
              500: '#6C727E',
              600: '#4D5761',
              700: '#384250',
              800: '#1F2A37',
              900: '#111927',
            },
          },
        },
        primary2: {
          pc: {
            indigo: {
              25: '#F5F8FF',
              50: '#EEF4FF',
              100: '#E0EAFF',
              200: '#C7D7FE',
              300: '#A3BBFD',
              400: '#7F98F9',
              500: '#6071F3',
              600: '#444CE7',
              700: '#3537CC',
              800: '#2D31A5',
              900: '#2D3282',
            },
          },
        },
        blue: {
          s: {
            info: {
              25: '#F4F9FF',
              50: '#EFF8FF',
              100: '#D1E9FF',
              200: '#B2DDFF',
              300: '#84CAFF',
              400: '#53B0FD',
              500: '#2E90FA',
            },
          },
        },
        green: {
          s: {
            success: {
              25: '#F6FFF9',
              50: '#ECFDF3',
              100: '#D1FADF',
              200: '#A6F4C5',
              300: '#6BE9A6',
              400: '#31D583',
              500: '#12B669',
            },
          },
        },
        orange: {
          s: {
            warning: {
              25: '#FFFCF5',
              50: '#FFFAEB',
              100: '#FEF0C7',
              200: '#FEDF89',
              300: '#FEC84B',
              400: '#FDB022',
              500: '#F79009',
            },
          },
        },
        red: {
          s: {
            error: {
              25: '#FFFBFA',
              50: '#FEF3F2',
              100: '#FEE4E2',
              200: '#FECDCA',
              300: '#FDA19B',
              400: '#F97066',
              500: '#F04437',
            },
          },
        },

        // Semantic Variables
        defaults: {
          primary: {
            'text-primary': '#111927',
            'text-primary-inverse': '#FCFCFD',
            'background-primary': '#FFFFFF',
            'background-primary-inverse': '#111927',
            'background-mono': '#FFFFFF',
            'background-mono-inverse': '#111927',
            'background-dimmed': '#00000080',
            'border-primary': '#D2D6DB',
            'border-primary-inverse': '#6C727E',
            'border-mono': '#384250',
            'border-mono-inverse': '#F9FAFB',
            'icon-primary': '#111927',
            'icon-primary-inverse': '#F3F4F6',
          },
          secondary: {
            'text-secondary': '#6C727E',
            'text-secondary-inverse': '#F3F4F6',
            'background-secondary': '#F3F4F6',
            'background-mono': '#F9FAFB',
            'background-mono-inverse': '#384250',
            'border-secondary': '#E5E7EB',
            'icon-secondary': '#6C727E',
          },
          tertiary: {
            'text-tertiary': '#9DA4AE',
            'background-tertiary': '#E5E7EB',
            'background-mono': '#F3F4F6',
            'background-mono-inverse': '#6C727E',
            'border-tertiary': '#F3F4F6',
            'icon-tertiary': '#9DA4AE',
          },
          hover: {
            'background-hover': '#F3F4F6',
            'border-hover': '#E5E7EB',
            'icon-hover': '#4D5761',
          },
          focus: {
            'text-focus': '#384250',
            'background-focus': '#E5E7EB',
            'border-focus': '#D2D6DB',
            'icon-focus': '#384250',
          },
          disabled: {
            'text-disabled': '#E5E7EB',
            'background-disabled': '#FFFFFF',
            'border-disabled': '#E5E7EB',
            'icon-disabled': '#E5E7EB',
          },
        },
        brand: {
          default: {
            'text-brand': '#2563EB',
            'text-brand-inverse': '#FFFFFF',
            'background-brand': '#2563EB',
            'border-brand': '#2563EB',
            'border-brand-inverse': '#FFFFFF',
            'icon-brand': '#2563EB',
            'icon-brand-inverse': '#FFFFFF',
          },
          hover: {
            'text-brand-hover': '#2563EB',
            'background-brand-hover': '#2563EB',
            'border-brand-hover': '#2563EB',
            'icon-brand-hover': '#2563EB',
          },
          focus: {
            'text-brand-focus': '#1A46A7',
            'background-brand-focus': '#1A46A7',
            'border-brand-focus': '#1A46A7',
            'icon-brand-focus': '#1A46A7',
          },
          disabled: {
            'text-brand-disabled': '#9BB7F6',
            'background-brand-disabled': '#9BB7F6',
            'border-brand-disabled': '#9BB7F6',
            'icon-brand-disabled': '#9BB7F6',
            'icon-brand-disabled-inverse': '#F9FBFF',
          },
        },
        alerts: {
          informal: {
            'text-informal': '#2E90FA',
            'background-informal': '#2E90FA',
            'background-informal-primary': '#EFF8FF',
            'background-informal-secondary': '#D1E9FF',
            'border-informal': '#2E90FA',
            'icon-informal': '#2E90FA',
            'icon-informal-hover': '#84CAFF',
            'icon-informal-focus': '#53B0FD',
            'icon-informal-disabled': '#B2DDFF',
          },
          success: {
            'text-success': '#12B669',
            'background-success': '#12B669',
            'background-success-primary': '#ECFDF3',
            'background-success-secondary': '#D1FADF',
            'border-success': '#12B669',
            'icon-success': '#12B669',
            'icon-success-hover': '#6BE9A6',
            'icon-success-focus': '#31D583',
            'icon-success-disabled': '#A6F4C5',
          },
          warning: {
            'text-warning': '#F79009',
            'background-warning': '#F79009',
            'background-warning-primary': '#FFFAEB',
            'background-warning-secondary': '#FEF0C7',
            'border-warning': '#F79009',
            'icon-warning': '#F79009',
            'icon-warning-hover': '#FEC84B',
            'icon-warning-focus': '#FDB022',
            'icon-warning-disabled': '#FEDF89',
          },
          error: {
            'text-error': '#F04437',
            'text-error-hover': '#FCA19B',
            'text-error-focus': '#F97066',
            'text-error-disabled': '#FECDCA',
            'background-error': '#F04437',
            'background-error-hover': '#FCA19B',
            'background-error-focus': '#F97066',
            'background-error-disabled': '#FECDCA',
            'background-error-primary': '#FEF3F2',
            'background-error-secondary': '#FEE4E2',
            'border-error': '#F04437',
            'icon-error': '#FCA19B',
            'icon-error-hover': '#F04437',
            'icon-error-focus': '#FCA19B',
            'icon-error-disabled': '#FEE2E2',
          },
        },
        charts: {
          'chart-mono': '#F3F4F6',
          'chart-brand': '#2563EB',
          'chart-first': '#5182EF',
          'chart-second': '#6D96F2',
          'chart-third': '#9BB7F6',
          'chart-fourth': '#BBCFF9',
        },
        'focus-ring': {
          'focus-primary': '#BBCFF9',
          'focus-secondary': '#F3F4F6',
          'focus-success': '#D1FADF',
          'focus-error': '#FEE4E2',
        },
      },
      spacing: {
        0: '1px',
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        7: '28px',
        8: '32px',
        9: '36px',
        10: '40px',
        11: '44px',
        12: '48px',
      },
      backgroundPosition: {
        'position-1': '25% 75%',
      },
      animation: {
        toggle: 'toggle 4s ease-in-out',
      },
      keyframes: {
        toggle: {
          '0%, 100%': { opacity: 0 },
          '25%, 75%': { opacity: 1 },
        },
      },
    },
  },
  plugins: [
    ({ addUtilities }) => {
      addUtilities({
        '.pretendard-h1': {
          fontFamily: 'Pretendard',
          fontSize: '36px',
          fontWeight: 800,
          lineHeight: '40px',
          letterSpacing: '-2.5%',
        },
        '.pretendard-h2': {
          fontFamily: 'Pretendard',
          fontSize: '30px',
          fontWeight: 600,
          lineHeight: '36px',
          letterSpacing: '-2.5%',
        },
        '.pretendard-h3': {
          fontFamily: 'Pretendard',
          fontSize: '24px',
          fontWeight: 600,
          lineHeight: '32px',
          letterSpacing: '-2.5%',
        },
        '.pretendard-h4': {
          fontFamily: 'Pretendard',
          fontSize: '20px',
          fontWeight: 600,
          lineHeight: '28px',
          letterSpacing: '-2.5%',
        },
        '.pretendard-h5': {
          fontFamily: 'Pretendard',
          fontSize: '18px',
          fontWeight: 600,
          lineHeight: '28px',
          letterSpacing: '-2.5%',
        },
        '.pretendard-p': {
          fontFamily: 'Pretendard',
          fontSize: '16px',
          fontWeight: 400,
          lineHeight: '28px',
        },
        '.pretendard-blockquote': {
          fontFamily: 'Pretendard',
          fontSize: '16px',
          fontWeight: 300,
          lineHeight: '28px',
        },
        '.pretendard-table-head': {
          fontFamily: 'Pretendard',
          fontSize: '16px',
          fontWeight: 700,
          lineHeight: '28px',
        },
        '.pretendard-table-item': {
          fontFamily: 'Pretendard',
          fontSize: '16px',
          fontWeight: 400,
          lineHeight: '28px',
        },
        '.pretendard-list': {
          fontFamily: 'Pretendard',
          fontSize: '16px',
          fontWeight: 400,
          lineHeight: '28px',
        },
        '.pretendard-lead': {
          fontFamily: 'Pretendard',
          fontSize: '20px',
          fontWeight: 400,
          lineHeight: '28px',
          color: '#64748B',
        },
        '.pretendard-large': {
          fontFamily: 'Pretendard',
          fontSize: '18px',
          fontWeight: 600,
          lineHeight: '28px',
        },
        '.pretendard-small': {
          fontFamily: 'Pretendard',
          fontSize: '14px',
          fontWeight: 500,
          lineHeight: '14px',
        },
        '.pretendard-muted': {
          fontFamily: 'Pretendard',
          fontSize: '14px',
          fontWeight: 400,
          lineHeight: '20px',
          color: '#64748B',
        },
        '.pretendard-link': {
          fontFamily: 'Pretendard',
          fontSize: '14px',
          fontWeight: 600,
          color: '#2563EB',
        },
        // 디자인시스템 2차
        '.pretendard-72Regular': {
          fontFamily: 'Pretendard',
          fontSize: '72px',
          fontWeight: 400,
          lineHeight: '111.11%' /* 79.999px */,
          letterSpacing: '-1.8px',
        },
        '.pretendard-72Medium': {
          fontFamily: 'Pretendard',
          fontSize: '72px',
          fontWeight: 500,
          lineHeight: '111.11%' /* 79.999px */,
          letterSpacing: '-1.8px',
        },
        '.pretendard-72Bold': {
          fontFamily: 'Pretendard',
          fontSize: '72px',
          fontWeight: 700,
          lineHeight: '111.11%' /* 79.999px */,
          letterSpacing: '-1.8px',
        },
        '.pretendard-64Regular': {
          fontFamily: 'Pretendard',
          fontSize: '64px',
          fontWeight: 400,
          lineHeight: '112.5%' /* 72px */,
          letterSpacing: '-1.8px',
        },
        '.pretendard-64Medium': {
          fontFamily: 'Pretendard',
          fontSize: '64px',
          fontWeight: 500,
          lineHeight: '112.5%' /* 72px */,
          letterSpacing: '-1.8px',
        },
        '.pretendard-64Bold': {
          fontFamily: 'Pretendard',
          fontSize: '64px',
          fontWeight: 700,
          lineHeight: '112.5%' /* 72px */,
          letterSpacing: '-1.8px',
        },
        '.pretendard-56Regular': {
          fontFamily: 'Pretendard',
          fontSize: '56px',
          fontWeight: 400,
          lineHeight: '114.28%' /* 63.997px */,
          letterSpacing: '-0.55px',
        },
        '.pretendard-56Medium': {
          fontFamily: 'Pretendard',
          fontSize: '56px',
          fontWeight: 500,
          lineHeight: '114.28%' /* 63.997px */,
          letterSpacing: '-0.55px',
        },
        '.pretendard-56Bold': {
          fontFamily: 'Pretendard',
          fontSize: '56px',
          fontWeight: 700,
          lineHeight: '114.28%' /* 63.997px */,
          letterSpacing: '-0.55px',
        },
        '.pretendard-44Regular': {
          fontFamily: 'Pretendard',
          fontSize: '44px',
          fontWeight: 400,
          lineHeight: '109.09%' /* 48px */,
          letterSpacing: '-0.55px',
        },
        '.pretendard-44Medium': {
          fontFamily: 'Pretendard',
          fontSize: '44px',
          fontWeight: 500,
          lineHeight: '109.09%' /* 48px */,
          letterSpacing: '-0.55px',
        },
        '.pretendard-44Bold': {
          fontFamily: 'Pretendard',
          fontSize: '44px',
          fontWeight: 700,
          lineHeight: '109.09%' /* 48px */,
          letterSpacing: '-0.55px',
        },
        '.pretendard-32Regular': {
          fontFamily: 'Pretendard',
          fontSize: '32px',
          fontWeight: 400,
          lineHeight: '125%' /* 40px */,
          letterSpacing: '-0.55px',
        },
        '.pretendard-32Medium': {
          fontFamily: 'Pretendard',
          fontSize: '32px',
          fontWeight: 500,
          lineHeight: '125%' /* 40px */,
          letterSpacing: '-0.55px',
        },
        '.pretendard-32Bold': {
          fontFamily: 'Pretendard',
          fontSize: '32px',
          fontWeight: 700,
          lineHeight: '125%' /* 40px */,
          letterSpacing: '-0.55px',
        },
        '.pretendard-24Regular': {
          fontFamily: 'Pretendard',
          fontSize: '24px',
          fontWeight: 400,
          lineHeight: '133.33%' /* 31.999px */,
          letterSpacing: '-0.55px',
        },
        '.pretendard-24Medium': {
          fontFamily: 'Pretendard',
          fontSize: '24px',
          fontWeight: 500,
          lineHeight: '133.33%' /* 31.999px */,
          letterSpacing: '-0.55px',
        },
        '.pretendard-24Bold': {
          fontFamily: 'Pretendard',
          fontSize: '24px',
          fontWeight: 700,
          lineHeight: '133.33%' /* 31.999px */,
          letterSpacing: '-0.55px',
        },
        '.pretendard-20Regular': {
          fontFamily: 'Pretendard',
          fontSize: '20px',
          fontWeight: 400,
          lineHeight: '140%' /* 28px */,
          letterSpacing: '-0.2px',
        },
        '.pretendard-20Medium': {
          fontFamily: 'Pretendard',
          fontSize: '20px',
          fontWeight: 500,
          lineHeight: '140%' /* 28px */,
          letterSpacing: '-0.2px',
        },
        '.pretendard-20SemiBold': {
          fontFamily: 'Pretendard',
          fontSize: '20px',
          fontWeight: 600,
          lineHeight: '140%' /* 28px */,
          letterSpacing: '-0.2px',
        },
        '.pretendard-20Bold': {
          fontFamily: 'Pretendard',
          fontSize: '20px',
          fontWeight: 700,
          lineHeight: '140%' /* 28px */,
          letterSpacing: '-0.2px',
        },
        '.pretendard-18Regular': {
          fontFamily: 'Pretendard',
          fontSize: '18px',
          fontWeight: 400,
          lineHeight: '144.44%' /* 25.999px */,
          letterSpacing: '-0.2px',
        },
        '.pretendard-18Medium': {
          fontFamily: 'Pretendard',
          fontSize: '18px',
          fontWeight: 500,
          lineHeight: '144.44%' /* 25.999px */,
          letterSpacing: '-0.2px',
        },
        '.pretendard-18SemiBold': {
          fontFamily: 'Pretendard',
          fontSize: '18px',
          fontWeight: 600,
          lineHeight: '144.44%' /* 25.999px */,
          letterSpacing: '-0.2px',
        },
        '.pretendard-16Regular': {
          fontFamily: 'Pretendard',
          fontSize: '16px',
          fontWeight: 400,
          lineHeight: '150%' /* 24px */,
          letterSpacing: '-0.16px',
        },
        '.pretendard-16Medium': {
          fontFamily: 'Pretendard',
          fontSize: '16px',
          fontWeight: 500,
          lineHeight: '150%' /* 24px */,
          letterSpacing: '-0.16px',
        },
        '.pretendard-16SemiBold': {
          fontFamily: 'Pretendard',
          fontSize: '16px',
          fontWeight: 600,
          lineHeight: '150%' /* 24px */,
          letterSpacing: '-0.16px',
        },
        '.pretendard-16Bold': {
          fontFamily: 'Pretendard',
          fontSize: '16px',
          fontWeight: 700,
          lineHeight: '150%' /* 24px */,
          letterSpacing: '-0.16px',
        },
        '.pretendard-14Regular': {
          fontFamily: 'Pretendard',
          fontSize: '14px',
          fontWeight: 400,
          lineHeight: '142.9%' /* 20.006px */,
        },
        '.pretendard-14Medium': {
          fontFamily: 'Pretendard',
          fontSize: '14px',
          fontWeight: 500,
          lineHeight: '142.9%' /* 20.006px */,
        },
        '.pretendard-14SemiBold': {
          fontFamily: 'Pretendard',
          fontSize: '14px',
          fontWeight: 600,
          lineHeight: '142.9%' /* 20.006px */,
        },
        '.pretendard-14Bold': {
          fontFamily: 'Pretendard',
          fontSize: '14px',
          fontWeight: 700,
          lineHeight: '142.9%' /* 20.006px */,
        },
        '.pretendard-12Regular': {
          fontFamily: 'Pretendard',
          fontSize: '12px',
          fontWeight: 400,
          lineHeight: '133.4%' /* 16.008px */,
        },
        '.pretendard-12Medium': {
          fontFamily: 'Pretendard',
          fontSize: '12px',
          fontWeight: 500,
          lineHeight: '133.4%' /* 16.008px */,
        },
        '.pretendard-12SemiBold': {
          fontFamily: 'Pretendard',
          fontSize: '12px',
          fontWeight: 600,
          lineHeight: '133.4%' /* 16.008px */,
        },
        '.pretendard-10Regular': {
          fontFamily: 'Pretendard',
          fontSize: '10px',
          fontWeight: 400,
          lineHeight: '140%' /* 14px */,
        },
        '.pretendard-10Medium': {
          fontFamily: 'Pretendard',
          fontSize: '10px',
          fontWeight: 500,
          lineHeight: '140%' /* 14px */,
        },
        '.pretendard-10SemiBold': {
          fontFamily: 'Pretendard',
          fontSize: '10px',
          fontWeight: 600,
          lineHeight: '140%' /* 14px */,
        },
        '.pretendard-8Regular': {
          fontFamily: 'Pretendard',
          fontSize: '8px',
          fontWeight: 400,
          lineHeight: '175%' /* 14px */,
        },
        '.pretendard-8Medium': {
          fontFamily: 'Pretendard',
          fontSize: '8px',
          fontWeight: 500,
          lineHeight: '175%' /* 14px */,
        },
        '.pretendard-8SemiBold': {
          fontFamily: 'Pretendard',
          fontSize: '8px',
          fontWeight: 600,
          lineHeight: '175%' /* 14px */,
        },
      });
    },
    ({ addComponents }) => {
      addComponents({
        '.select-background-position-custom': {
          backgroundPosition: 'top 50% right 12px',
        },
        '.scroll-hidden::-webkit-scrollbar': {
          // Chrome, Safari, Opera
          display: 'none',
        },
        '.show-recent-entry': { '.recent-entry': { display: 'block' } },
      });
    },
  ],
};
